### PR TITLE
Update HAProxy version to latest LTS

### PR DESCRIPTION
**Pull request by smorimoto**
I believe this PR bumped the base Debian version: https://github.com/docker-library/postgres/pull/1098

https://github.com/docker-library/postgres/blob/3fda89cc5c2e588f46ae4f1ac117114c8e6814f1/15/bookworm/Dockerfile#LL7C1-L7C5

### CODE REVIEW

**Comment by smorimoto** [comment]
Can anyone review this?

**Comment by davissp14** [comment]
@smorimoto I'll do my best to take a look at this tomorrow!

**Comment by smorimoto** [comment]
@davissp14 Thank you so much!

**Comment by davissp14** [comment]
Looks like the build is failing with:

```
 => ERROR [stage-2  6/11] RUN apt-get update && apt-get install --no-install-recommends -y     haproxy=2.7.*     && apt autoremove -y                                                                                                                                                                                                                                6.8s
------
 > [stage-2  6/11] RUN apt-get update && apt-get install --no-install-recommends -y     haproxy=2.7.*     && apt autoremove -y:
#11 0.763 Hit:1 http://deb.debian.org/debian bookworm InRelease
#11 0.763 Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
#11 0.791 Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
#11 0.869 Ign:4 http://haproxy.debian.net bookworm-backports-2.7 InRelease
#11 0.908 Hit:5 http://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease
#11 0.953 Err:6 http://haproxy.debian.net bookworm-backports-2.7 Release
#11 0.953   404  Not Found [IP: 5.161.44.145 80]
#11 3.863 Reading package lists...
#11 6.819 E: The repository 'http://haproxy.debian.net bookworm-backports-2.7 Release' does not have a Release file.
------
executor failed running [/bin/sh -c apt-get update && apt-get install --no-install-recommends -y     haproxy=$HAPROXY_VERSION.\*     && apt autoremove -y]: exit code: 100
```

Are you seeing the same thing when you run the following? 

```
docker build .  --platform linux/amd64
```

**Comment by smorimoto** [comment]
HAProxy 2.7 does not exist in the bookworm, so we have to merge #204 first.

**Comment by smorimoto** [comment]
Sure. 私はこちらのPRに全てを統合しますね。

**Comment by smorimoto** [comment]
(Sorry. I woke up and was sleepy, so I wrote a comment in Japanese 😅)

Makes sense! I will merge another one into this PR.

**Comment by smorimoto** [comment]
Done 🙂

**Comment by davissp14** [comment]
Looks good!  Thank you and sorry for the delay!

**Comment by smorimoto** [comment]
When will the new version be released?

**Pull request merged**
