### PR TITLE
Update `PG_VERSION` to 15.3

### PR DESCRIPTION
**Pull request by smorimoto**
As the title says!

### CODE REVIEW

**Comment by davissp14** [comment]
@smorimoto Thanks for the PR!  We will also need to update the CI workflow to point to the new version:
https://github.com/fly-apps/postgres-flex/blob/master/.github/workflows/ci.yaml#L35-L63

**Comment by smorimoto** [comment]
@davissp14 I'm complaining that my grep wouldn't have caught it! 😵‍💫 I believe I corrected it! 🙂

**Comment by davissp14** [comment]
@smorimoto  It's close!  There's a few more references to update in that ci file. 

https://github.com/fly-apps/postgres-flex/blob/9d5b688a292ac2a92e8ef693741ba9fa4cb4e37a/.github/workflows/ci.yaml#L48-L63

**Comment by smorimoto** [comment]
Ooooops 🤯 Eye-grep was not better!

**Comment by davissp14** [comment]
Looks great, thank you!

**Pull request merged**
